### ISSUE TITLE
when run search using res50, get errors

### ISSUE THREAD

**Issue by cs-heibao** [anonymous47823493/EagleEye#16]
@anonymous47823493 
during the generation of stategy, sometimes get error:
```
USE PART OF TRAIN SET WITH UNIFORM SPLIT
len(train_dataset) 12724
FLOPs ratio: 0.4226975629989995
USE PART OF TRAIN SET WITH UNIFORM SPLIT
len(train_dataset) 12724
FLOPs ratio: 0.3743268191985986
USE PART OF TRAIN SET WITH UNIFORM SPLIT
len(train_dataset) 12724
Traceback (most recent call last):
  File "/media/jie/Work/EagleEye-master/search.py", line 104, in <module>
    main(opt)
  File "/media/jie/Work/EagleEye-master/search.py", line 70, in main
    thinning(net, compression_scheduler, input_tensor=dummy_input)
  File "/media/jie/Work/EagleEye-master/thinning/__init__.py", line 12, in thinning
    scheduler.on_epoch_begin(1)
  File "/media/jie/Work/EagleEye-master/distiller/scheduler.py", line 129, in on_epoch_begin
    policy.on_epoch_begin(self.model, self.zeros_mask_dict, meta, **kwargs)
  File "/media/jie/Work/EagleEye-master/distiller/policy.py", line 197, in on_epoch_begin
    self.pruner.set_param_mask(param, param_name, zeros_mask_dict, meta)
  File "/media/jie/Work/EagleEye-master/distiller/pruning/ranked_structures_pruner.py", line 63, in set_param_mask
    param, param_name, zeros_mask_dict, fraction_to_prune, model
  File "/media/jie/Work/EagleEye-master/distiller/pruning/ranked_structures_pruner.py", line 85, in prune_to_target_sparsity
    assert self.leader_binary_map is not None
AssertionError
```

**Comment by Bowenwu1** [comment]
Would you please share your python command/shell script for above error?

**Comment by cs-heibao** [comment]
@Bowenwu1 
hi, I use the pycharm to run

**Comment by cs-heibao** [comment]
@Bowenwu1 
I'm also run the shell script on the moment, but get the same error
the shell script is :
```
###### 1. Search ######
python3 search.py \
--model_name resnet50 \
--num_classes 1000 \
--checkpoint models/ckpt/resnet50_50flops.pth \
--gpu_ids 0 \
--batch_size 64 \
--dataset_path /media/jie/Work/Public_Transportation_project/DALIprocess/ImageNet2012 \
--dataset_name imagenet_train_val_split \
--num_workers 4 \
--flops_target 0.5 \
--max_rate 0.7 \
--output_file log.txt \
--compress_schedule_path compress_config/res50_imagenet.yaml
```

**Comment by Bowenwu1** [comment]
@cs-heibao How do set your arguments? Like `--model_name`, `--max_rate`?

**Comment by cs-heibao** [comment]
`--model_name resnet50`
`--max_rate 0.7`

**Comment by Bowenwu1** [comment]
@cs-heibao You could try to re-run the above command. I am working on reproducing the above error, please wait for a moment.

**Comment by cs-heibao** [comment]
@Bowenwu1 
as follows:
![image](https://user-images.githubusercontent.com/33689425/90211878-8e8cc300-de24-11ea-95ed-57b0c6eee684.png)

**Comment by cs-heibao** [comment]
@Bowenwu1 
the first time it runs normally, and can print("Eval Score:{}".format(strategy_score)),
when do another search, it corrupts

**Comment by Bowenwu1** [comment]
It seems a pytorch/cuda version issue.
Please try to check `pip freeze`, `nvidia-smi`, `python -c "import torch;torch.version.cuda"

**Comment by cs-heibao** [comment]
@Bowenwu1 
![image](https://user-images.githubusercontent.com/33689425/90217610-673df200-de34-11ea-8e37-5d9a26212a99.png)

**Comment by Bowenwu1** [comment]
@cs-heibao 
If you want to perform search by yourself. You need to use `--checkpoint models/ckpt/resnet50_imagenet.pth` rather than `--checkpoint models/ckpt/resnet50_50flops.pth`.

`resnet50_50flops.pth` is already the checkpoint of pruned model, while `resnet50_imagenet.pth` is a pretrained full model.

**Comment by cs-heibao** [comment]
@Bowenwu1 
but the dropbox link you provide do not have the pretrained full model resnet50_imagenet.pth, thanks

**Comment by cs-heibao** [comment]
@Bowenwu1 
I changed the `checkpoint models/ckpt/resnet50_50flops.pth` to `--checkpoint models/ckpt/resnet50_imagenet.pth`, but seems not work, thanks

**Comment by Bowenwu1** [comment]
@cs-heibao This is caused by distiller can not support a pruning rate of 0. I have fixed it on [commit](https://github.com/anonymous47823493/EagleEye/commit/84924eac07713714b5b0c1db1c4a0b46a8da6d5a), please try it out.

Sorry for bothering you.

**Comment by cs-heibao** [comment]
@Bowenwu1 
thanks for you help, it fixed now.
another question about some scripts: `search.py`, `choose_strategy.py`, and `finetune.py`,
after read your paper and got my own understanding(but I can not make sure whether it is right),
1) as for `search.py`, the main purpose is to get the strategy_score, ratio and the corresponding channel_config items, I use the pretrained full model to prune, but after prune and do the evaluation, the scores keep 0 all the time, so how do I to choose a best candidate strategy?
2) but I don't know the actual mean, just to get the first 5 strategey and print it out?
```
for i in range(5):
    print(
        "strategy index:{}, score:{}".format(
            score_sorted_index[i], score[score_sorted_index[i]]
        )
    )
print("\n")
```
3) finetune.py file, based on search.py add the fine-tuning train module, use the `opt.search_result`, and `opt.strategy_id` to fine tune the corresponding sub-net. Here, the parameter `opt.strategy_id` (0, default), actually, the value of `opt.strategy_id` is the best candidate strategy's corresponding index, which should defined by myself??? But as above said, the evaluation's score of all prune strategy is zero, how do I confirm a best one?
thanks!

**Comment by Bowenwu1** [comment]
@cs-heibao 
Your understanding is right. Thanks for reading our paper carefully!

The phenomenon of "evaluation's score of all prune strategy is zero" is unusual.  I think it might be the `--batch_size` affect the effect of ABN. Please try `--batch_size=128` for searching of ResNet50, which is the setting of our experiments.

Sorry for bothering you for hyper-parameters, we will release full scripts for all cases.

**Comment by Bowenwu1** [comment]
@cs-heibao 
After you change `--batch_size`, please check eval score is not zero first.

**Comment by cs-heibao** [comment]
@Bowenwu1 
I just want to discuss with you, I do as you said change `--batch_size` to 128, but it seems the same, the eval score is still zero.
I wonder batch_size should not influence the eval score to always keep zero, could it be the pretrained full model is wrong or the val dataset exits problem? I will check the val dataset immediately, and the same time could you share me your pretrained full model of resnet50_imagenet? thanks

**Comment by Bowenwu1** [comment]
@cs-heibao 
The pretrained full model indeed will influence the eval score.

The pretrained model could be found in [dropbox](https://www.dropbox.com/sh/im1janxv5p8u5jm/AAA7s6danrqdL42UvteICARra?dl=0)

**Comment by cs-heibao** [comment]
@Bowenwu1 
hi, I tried many times and use your provided pretrained full model `imagenet_resnet50_76.pth`, what's more I use the train dataset as the val dataset, but the scores still zero.
I just run `python search.py` on terminal, have you tried this and what's your run result?
part of train dataset 
![image](https://user-images.githubusercontent.com/33689425/90355243-600a2480-e07e-11ea-9278-373ef8b229e4.png)

**Comment by cs-heibao** [comment]
@Bowenwu1 
1)a strange phenomenon, I commit `# #####################  Pruning Strategy Generation ###############`
`# ###### Adaptive-BN-based Candidate Evaluation of Pruning Strategy ###` in `search.py`, that is to say, use the pretrained full model directly without prune, and `strategy_score = net.get_eval_scores(dataloader_val)["accuracy"]` also is zero.
2)as mentioned above, even though the eval scores always keep zero, but if I finetune a epoch, the scores can reach to 0.56(more epochs, more scores)
so, as for 1), is the pretrained full model is not fit the data?

**Comment by Bowenwu1** [comment]
@cs-heibao 
I'm trying to run this code with your setting by myself.

I'm wondering whether your ImageNet is different with ours? As I have known, ImageNet has two versions of labels.

**Comment by Bowenwu1** [comment]
<img width="1440" alt="截屏2020-08-17 下午10 00 42" src="https://user-images.githubusercontent.com/16816766/90404646-447e3880-e0d5-11ea-91b7-fd6062972030.png">

I have tried to run this code. And the output like above.
As you can see, the eval score is not zero. So there must be other reasons that cause your problem.

**Comment by cs-heibao** [comment]
@Bowenwu1 
hi, the original dataset should not be like this? I just extract ten folders as my train dataset(since total data are too larger)
![image](https://user-images.githubusercontent.com/33689425/90465196-70370800-e141-11ea-8879-1a2eef3fa1f0.png)

**Comment by Bowenwu1** [comment]
@cs-heibao 
Oh!  I think that's the problem.

We use all 1000 classes of ImageNet for training/searching. If you only use 10 classes of it, it will be hard to guarantee that the labels will accurately match our provided pretrained model. For example, your `label 1` may match our `label 347`. Moreover, ABN with 10 classes of data can not work well since too limited data.

**Comment by cs-heibao** [comment]
@Bowenwu1 
as you said, it maybe mismatch actually, thanks for your patient guidance. And next I will try to combine it with my own project, maybe also need your help, thanks

**Comment by xialei1020** [comment]
> @Bowenwu1
> I'm also run the shell script on the moment, but get the same error
> the shell script is :
> 
> ```
> ###### 1. Search ######
> python3 search.py \
> --model_name resnet50 \
> --num_classes 1000 \
> --checkpoint models/ckpt/resnet50_50flops.pth \
> --gpu_ids 0 \
> --batch_size 64 \
> --dataset_path /media/jie/Work/Public_Transportation_project/DALIprocess/ImageNet2012 \
> --dataset_name imagenet_train_val_split \
> --num_workers 4 \
> --flops_target 0.5 \
> --max_rate 0.7 \
> --output_file log.txt \
> --compress_schedule_path compress_config/res50_imagenet.yaml
> ```

Could you share ur imagenet2012 dataset to me, i can‘t download it, thanks！

**Comment by Bowenwu1** [comment]
@xialei1020 
Hi~
Which error do you mean?

**Comment by Bowenwu1** [comment]
@cs-heibao 
You're welcome. Thanks for your attention to our paper, and we're glad to hear you want to combine it in your own project.

If you have any questions, any kinds of discussion is welcome here.

**Comment by xialei1020** [comment]
你好！关于eagleeye，你在search result里面给了mobilenetv1的搜索结果，然后默认也是mobilenetv1，我想请问一下如果我想搜索resnet50的话，我的python命令中，search result该是什么样的，谢谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anonymous47823493/EagleEye"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上7:22
收件人:&nbsp;"anonymous47823493/EagleEye"<EagleEye@noreply.github.com&gt;;
抄送:&nbsp;"雨过天晴"<243698844@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [anonymous47823493/EagleEye] when run search using res50, get errors (#16)





 
@cs-heibao
 You're welcome. Thanks for your attention to our paper, and we're glad to hear you want to combine it in your own project.
 
If you have any questions, any kinds of discussion is welcome here.

**Comment by cs-heibao** [comment]
@xialei1020 
```
###### 1. Search ######
python3 search.py \
--model_name resnet50 \
--num_classes 1000 \
--checkpoint models/ckpt/resnet50_imagenet.pth \
--gpu_ids 0 \
--batch_size 64 \
--dataset_path /media/jie/Work/Public_Transportation_project/DALIprocess/ImageNet2012 \
--dataset_name imagenet_train_val_split \
--num_workers 4 \
--flops_target 0.5 \
--max_rate 0.7 \
--output_file log.txt \
--compress_schedule_path compress_config/res50_imagenet.yaml
```
checkpoint models in the [dropbox](https://www.dropbox.com/sh/im1janxv5p8u5jm/AAA7s6danrqdL42UvteICARra?dl=0) links named imagenet_resnet50_76.pth

**Comment by khushboo-anand0909** [comment]
@cs-heibao Were you able to get eval score more than zero after using complete dataset. The one I downloaded from ImageNet website seems to be a subset even though the class names are same but the eval scores are still zero. Can you please share the exact link of ImageNet dataset you used for experimenting?
