### ISSUE TITLE
where is the main.py?

### ISSUE THREAD

**Issue by luyitry** [anonymous47823493/EagleEye#17]
@anonymous47823493 
![image](https://user-images.githubusercontent.com/54425313/91793151-f119f780-ec49-11ea-920f-5822eb1208f9.png)

**Comment by Bowenwu1** [comment]
The `main.py` have changed to `infernece.py`.

The readme is already updated at [commit](https://github.com/anonymous47823493/EagleEye/commit/2fe5653bb3a7228f9522e3212b6d9011fa50a6b7).
