### ISSUE TITLE
Question about  pruning_strategies.txt generated by search.py.

### ISSUE THREAD

**Issue by BlossomingL** [anonymous47823493/EagleEye#18]
Hi~
I have run search.py on MobileNetV1 (with your mbv1_50flops.sh ) and got 400 records in pruning_strategies.txt, but didn't reach your max accuracy 0.143, I just get max accuracy 0.062,  is anything wrong?

**Comment by Bowenwu1** [comment]
@BlossomingL 
hi~ how many strategies do you search?

**Comment by BlossomingL** [comment]
> @BlossomingL
> hi~ how many strategies do you search?

958

**Comment by bezorro** [comment]
> > @BlossomingL
> > hi~ how many strategies do you search?
> 
> 958, max accuracy 0.069

Which pre-trained weight did you use? Did you use our [provided weight](https://drive.google.com/file/d/1Uskkhu9EbA8nSYPqpmgs9qwVr0FQYM_v/view?usp=sharing)?

**Comment by BlossomingL** [comment]
> > > @BlossomingL
> > > hi~ how many strategies do you search?
> > 
> > 
> > 958, max accuracy 0.069
> 
> Which pre-trained weight did you use? Did you use our [provided weight](https://drive.google.com/file/d/1Uskkhu9EbA8nSYPqpmgs9qwVr0FQYM_v/view?usp=sharing)?

**Comment by BlossomingL** [comment]
Yes, I download from your google drive.

**Comment by BlossomingL** [comment]
```python
python3 search.py \
--model_name mobilenetv1 \
--num_classes 1000 \
--checkpoint models/ckpt/imagenet_mobilenet_full_model.pth \
--gpu_ids 0 \
--batch_size 128 \
--dataset_path /home/linx/dataset/ImageNet2012 \
--dataset_name imagenet_train_val_split \
--num_workers 4 \
--flops_target 0.5 \
--max_rate 0.7 \
--output_file search_results/pruning_strategies.txt \
--compress_schedule_path compress_config/mbv1_imagenet.yaml
```

**Comment by bezorro** [comment]
> This is my scripts.
> 
> ```python
> python3 search.py \
> --model_name mobilenetv1 \
> --num_classes 1000 \
> --checkpoint models/ckpt/imagenet_mobilenet_full_model.pth \
> --gpu_ids 0 \
> --batch_size 128 \
> --dataset_path /home/linx/dataset/ImageNet2012 \
> --dataset_name imagenet_train_val_split \
> --num_workers 4 \
> --flops_target 0.5 \
> --max_rate 0.7 \
> --output_file search_results/pruning_strategies.txt \
> --compress_schedule_path compress_config/mbv1_imagenet.yaml
> ```

Ok, I think there won't be anything wrong.
The random search algorithm may not be quite stable, please try more candidates and you may get some strategies above 0.10.
Run more processes parallelly would accelerate the searching phase, which is inherently supported in our code by the [adding up mechanism](https://github.com/anonymous47823493/EagleEye/blob/master/search.py#L96) for the searching results.
Glad to see your update for the best strategy.

**Comment by BlossomingL** [comment]
Another problem: when I run finetune.py with your provided scripts and checkpoint, errors as follow:
```
Traceback (most recent call last):
  File "finetune.py", line 173, in <module>
    main(opt)
  File "finetune.py", line 90, in main
    net.load_checkpoint(opt.checkpoint)
  File "/home/yeluyue/lz/program/EagleEye/models/wrapper.py", line 122, in load_checkpoint
    module.weight = torch.nn.Parameter(checkpoint[key + ".weight"])
KeyError: 'layers.0.conv1.weight'
```
