### ISSUE TITLE
Another problem: when I run finetune.py with your provided scripts and checkpoint, errors as follow:

### ISSUE THREAD

**Issue by bezorro** [anonymous47823493/EagleEye#19]
Another problem: when I run finetune.py with your provided scripts and checkpoint, errors as follow:
```
Traceback (most recent call last):
  File "finetune.py", line 173, in <module>
    main(opt)
  File "finetune.py", line 90, in main
    net.load_checkpoint(opt.checkpoint)
  File "/home/yeluyue/lz/program/EagleEye/models/wrapper.py", line 122, in load_checkpoint
    module.weight = torch.nn.Parameter(checkpoint[key + ".weight"])
KeyError: 'layers.0.conv1.weight'
```

_Originally posted by @BlossomingL in https://github.com/anonymous47823493/EagleEye/issues/18#issuecomment-689932416_

**Comment by bezorro** [comment]
It seems that the model does not match the pre-trained weight.
Can I see your script?

**Comment by bezorro** [comment]
It seems that the model does not match the pre-trained weight.
Can I see your script?
@BlossomingL

**Comment by BlossomingL** [comment]
```python
python3 finetune.py \
--model_name mobilenetv1 \
--num_classes 1000 \
--checkpoint models/ckpt/imagenet_mobilenet_full_model.pth \
--gpu_ids 0 \
--batch_size 512 \
--dataset_path /home/yeluyue/lz/dataset/ImageNet2012 \
--dataset_name imagenet \
--exp_name mbv1_50flops_3 \
--search_result search_results/best_strategy_mbv1_50flops.txt \
--strategy_id 1 \
--epoch 120 \
--lr 1e-2 \
--weight_decay 5e-4
```

**Comment by bezorro** [comment]
> ```python
> python3 finetune.py \
> --model_name mobilenetv1 \
> --num_classes 1000 \
> --checkpoint models/ckpt/imagenet_mobilenet_full_model.pth \
> --gpu_ids 0 \
> --batch_size 512 \
> --dataset_path /home/yeluyue/lz/dataset/ImageNet2012 \
> --dataset_name imagenet \
> --exp_name mbv1_50flops_3 \
> --search_result search_results/best_strategy_mbv1_50flops.txt \
> --strategy_id 1 \
> --epoch 120 \
> --lr 1e-2 \
> --weight_decay 5e-4
> ```

Try `>> print(torch.load(opt.checkpoint).keys())` to see if the loaded weight matches the model.

**Comment by BlossomingL** [comment]
OK, thanks, I have solved it.

**Comment by BlossomingL** [comment]
I also search max accuracy on ResNet-50, the top-5 accuracy as follow, can I prune and finetune ResNet-50 on these parameters?
```
strategy index:49, score:0.133
strategy index:165, score:0.122
strategy index:94, score:0.117
strategy index:290, score:0.102
strategy index:22, score:0.101
```

**Comment by bezorro** [comment]
> OK, thanks, I have solved it.

Why the bug occured, is there a bug inside our code?

**Comment by BlossomingL** [comment]
> > OK, thanks, I have solved it.
> 
> Why the bug occured, is there a bug inside our code?

No, it's my careless.
