### ISSUE TITLE
Search for ResNet-50

### ISSUE THREAD

**Issue by bezorro** [anonymous47823493/EagleEye#20]
I also search max accuracy on ResNet-50, the top-5 accuracy as follow, can I prune and finetune ResNet-50 on these parameters?
```
strategy index:49, score:0.133
strategy index:165, score:0.122
strategy index:94, score:0.117
strategy index:290, score:0.102
strategy index:22, score:0.101
```

_Originally posted by @BlossomingL in https://github.com/anonymous47823493/EagleEye/issues/19#issuecomment-689951299_

**Comment by Bowenwu1** [comment]
@BlossomingL

Sure, you could have a try.

What pruning target do you use here?

**Comment by BlossomingL** [comment]
```python
python3 search.py \
--model_name resnet50 \
--num_classes 1000 \
--checkpoint models/ckpt/imagenet_resnet50_full_model.pth \
--gpu_ids 0 \
--batch_size 128 \
--dataset_path /home/linx/dataset/ImageNet2012 \
--dataset_name imagenet_train_val_split \
--num_workers 4 \
--flops_target 0.5 \
--max_rate 0.7 \
--output_file search_results/pruning_strategies_resnet50.txt \
--compress_schedule_path compress_config/res50_imagenet.yaml
```

**Comment by bezorro** [comment]
@BlossomingL 
It seems that your seaching configuration and searching results are correct. Thanks for sharing.
We will release the scripts for ResNet-50 soon.
