### ISSUE TITLE
Question about pruning MobileFaceNet on face recognition.

### ISSUE THREAD

**Issue by BlossomingL** [anonymous47823493/EagleEye#22]
Hi~
I have successfully re-implemented your baseline. Now I want to prune MobileFaceNet on face recognition with your idea. But when I search for the best score, I found it's always 0. My scores calculation script is same as yours.

**Comment by bezorro** [comment]
There may be a lot of reasons for this.
I suggest you to debug by setting the pruning rates to **zero** and some small values **close to zero** and see whether the pruning phase work well

**Comment by BlossomingL** [comment]
> There may be a lot of reasons for this.
> I suggest you to debug by setting the pruning rates to **zero** and some small values **close to zero** and see whether the pruning phase works well.

Thanks for your reply!
I have searched for 500 iterations and got search results as follow:
```
strategy index:127, score:0.051
strategy index:120, score:0.04
strategy index:265, score:0.031
strategy index:167, score:0.027
strategy index:235, score:0.018
```
My flops target is 0.5, and original accuracy is 0.98, but the pruned accuracy is too low, do you have any suggestion?

**Comment by Bowenwu1** [comment]
@BlossomingL 
Your search score looks OK so far.
There's 2 suggestion: 1. Try different search space, a good search space helps a lot. 2. Try to increase the number of iterations of ABN-process.

**Comment by gkrisp98** [comment]
> Hi~ I have successfully re-implemented your baseline. Now I want to prune MobileFaceNet on face recognition with your idea. But when I search for the best score, I found it's always 0. My scores calculation script is same as yours.

Hi there, I am trying to implement the EagleEye to prune a face detector but I am facing some problems. Could you provide me some guides on how you achieved to implement this ?
