### ISSUE TITLE
Question on detailed implementation

### ISSUE THREAD

**Issue by ShawnHu98** [anonymous47823493/EagleEye#24]

**Comment by ShawnHu98** [comment]
1. You mentioned "Please refer to supplementary material" in your paper, but I can't find it. Could you please relase it somewhere?
2. Is there any hint on the effect of the hyper-parameter "max_iter" in A-BN-E algorithm?
3. Gentle suggestion: maybe you could relase the "imagenet_train_val_split_idx.pickle", because it's small but time-comsuming to get.
4. Thank you for your valuable paper and codes!

**Comment by Bowenwu1** [comment]
2.
"max_iter" for A-BN-E: Actually the effect of this hyper-parameter is very similar to "max_steps" while training NN. The performance of the network will continue to improve while increasing the steps of ABN, and it will come to convergence at certain steps.
"batch size" for A-BN-E: In terms of our experience, a small batch size will make ABN less effective. 128 for MobileNetV1 and ResNet50 will be OK. A proper `batch_size` of ABN should make the score looks reasonable.

3. Thanks for your suggestion. I have uploaded this file on this [commit](https://github.com/anonymous47823493/EagleEye/commit/1c2c2e00a94136241227aa972ae9f5662ce8e0f0).

4. It's our pleasure to present our paper to you!

**Comment by ShawnHu98** [comment]
Thank you for your kind response. But could you please explain more details for me? That would be truly helpful.

1. How many epochs of finetune you use to reproduce the Acc. in your paper? 
The supp material mentions that you use 30 epochs, which is not the same as the 120 epoch in your example scripts.

2. How do you split the CIFAR-10 dataset for A-BN-E algorithm?  And how do you set the "max_steps" for CIFAR-10？

Thank you in advance.

**Comment by Bowenwu1** [comment]
1. The 30 epoches setting is used for correlation study on CIFAR10. As shown in the sec3 of supp, for the pruning experiments on CIFAR10, 350 epoches setting is employed.

And the 120 epoch is used for ImageNet pruning experiments.

**Comment by ShawnHu98** [comment]
Thank you!
