### ISSUE TITLE
about cifar10

### ISSUE THREAD

**Issue by icey-zhang** [anonymous47823493/EagleEye#27]
您好，请问可以公开cifar10部分的代码和实验结果吗？

**Comment by syswyl** [comment]
> 您好，请问可以公开cifar10部分的代码和实验结果吗？
您好 请问您为什么close这个issue呢 是已经成功复现了吗，处理imagenet对我测试而言太大了。我在处理cifar10时候有些问题，可以交流一下吗

**Comment by syswyl** [comment]
> 您好，请问可以公开cifar10部分的代码和实验结果吗？

您好 请问您为什么close这个issue呢 是已经成功复现了吗，处理imagenet对我测试而言太大了。我在处理cifar10时候有些问题，可以交流一下吗
