### ISSUE TITLE
the ratios  Problems in searching ResNet50

### ISSUE THREAD

**Issue by Crownwzt** [anonymous47823493/EagleEye#28]
FLOPS ratio：0.98236
FLOPS ratio：0.97435
FLOPS ratio：0.96765
FLOPS ratio：0.99743
FLOPS ratio：0.97125
FLOPS ratio：0.95743
............
today，we want to follow the code in your paper, but when we ues the res50_50flops.sh, we find the strategy generation is always range 0.96~1 is far away from the target flops ratios. we use the parameters in the code you provide. can you help me to reproduce the work?

**Comment by Bowenwu1** [comment]
hi
The problem is very strange and we will help you to figure it out.
Could you show the command you used?

**Comment by Crownwzt** [comment]
Thank you for your help，the command we used is as follow :
###### 1. Search ######
python3 search.py \
--model_name resnet50 \
--num_classes 1000 \
--checkpoint models/ckpt/imagenet_resnet50_full_model.pth \
--gpu_ids 0 \
--batch_size 128 \
--dataset_path /data/imagenet \
--dataset_name imagenet_train_val_split \
--num_workers 4 \
--flops_target 0.5 \
--max_rate 0.7 \
#--affine 0 \
--output_file search_results/res50_50flops_strategies.txt \
--compress_schedule_path compress_config/res50_imagenet.yaml
and the log begin with
USE PATH OF TRAIN...
len(train_dataset) 1281167
FLOPS ratio：0.98236
FLOPS ratio：0.97435
FLOPS ratio：0.96765
......
and we print the channel config in search.py is a list length14 and the value between 0.1~0.6, it seems normal.

**Comment by Crownwzt** [comment]
We have run more than 2000 iterations, and the FLOPS ratio is range 0.96~1.

**Comment by Bowenwu1** [comment]
Your scripts seem OK. Is there any content on the output file?

**Comment by Bowenwu1** [comment]
`search_results/res50_50flops_strategies.txt`

**Comment by Crownwzt** [comment]
beacuse the FLOPS ratio is not satisfied with the condition, the code will return to main， so there is no result in search_results/res50_50flops_strategies.txt

**Comment by Crownwzt** [comment]
May i have your wechat num to fix the problem?

**Comment by Bowenwu1** [comment]
Please email me at bowen.wu@163.com, I will give you my wechat num.
