### ISSUE TITLE
while True

### ISSUE THREAD

**Issue by chwwade** [anonymous47823493/EagleEye#32]
I see “while True：” in finetune.py,how can we jump out it?

**Comment by Bowenwu1** [comment]
Thanks for pointing out this. This issue is already fixed at this [commit](https://github.com/anonymous47823493/EagleEye/commit/f653fdaf2f05c6eff07dbae84b3b3f160696cb88).

**Comment by chwwade** [comment]
In search.py ，“while true” is also existing。Does it need fixing？

**Comment by Bowenwu1** [comment]
@chwwade 
"while True" is needed at search.py
