### ISSUE TITLE
Question for full-size baseline model performance in paper's Table.4 and Table.5

### ISSUE THREAD

**Issue by dercaft** [anonymous47823493/EagleEye#40]
Hello: 
What's your full-size baseline model performance in Table.4 and Table.5?
In your paper, there is only compressed baseline model performance, eg. 0.75× ResNet-50's Acc 74.8%
But in other works, they usually use full-size baseline model as a comparison.
So I wondered what's your full-size baseline.
Looking for your reply.
Thank you.

**Comment by Bowenwu1** [comment]
The acc of our full ResNet-50 is 77.2%.
The acc of our full MobileNetV1 is 72.62%.

For details of our full models, you can refer to https://drive.google.com/drive/folders/1ENq4RuFey3J2iL-Lu1BZ9ToTYILpV9bC for full model checkpoints.
